#!/bin/sh

SOCKET_PATH="/run/user/0/wayland-0"

while [ ! -S "$SOCKET_PATH" ]; do
    echo "Waiting for Wayland compositor to be ready..."
    sleep 1
done

QT_IVI_SURFACE_ID=1000 head-unit -platform wayland &
QT_IVI_SURFACE_ID=2000 instrument-cluster -platform wayland &
