#!/bin/sh
### BEGIN INIT INFO
# Provides:          can-setup
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CAN interface setup
### END INIT INFO

case "$1" in
    start)
        echo "Setting up CAN interface"
        ip link set can0 up type can bitrate 500000
        ;;
    stop)
        echo "Shutting down CAN interface"
        ip link set can0 down
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
